version: '2.0'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=3000
    ports:
      - 9496:3000
    networks:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  database:
    name: database
    external: true
