version: '2.0'

services:
  warproxy:
    image: ghcr.io/toshu-company/warproxy:latest
    restart: always
    environment:
      - WARP_PLUS=true
    expose:
      - 1080
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=3000
    ports:
      - 9496:3000
    networks:
      - default
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  database:
    name: database
    external: true
